### ISSUE TITLE
Running 'script/download-weights' in Docker with the current directory mounted as a volume... [FATAL tini (8)] exec script/download-weights failed: No such file or directory

### ISSUE THREAD

**Issue by demoBBB** [AsiryanOnReplicate/cog-flux-schnell-text2img-img2img#1]
sudo cog run script/download-weights
Building Docker image from environment in cog.yaml...
[+] Building 3.3s (12/12) FINISHED                                                                       docker:default
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 550B                                                                               0.0s
 => resolve image config for docker-image://docker.io/docker/dockerfile:1.4                                        2.4s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84  0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 425B                                                                                  0.0s
 => [internal] load metadata for r8.im/cog-base:cuda12.1-python3.11                                                0.7s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 443B                                                                                  0.0s
 => [1/5] FROM r8.im/cog-base:cuda12.1-python3.11@sha256:cc87170dd619e13a319738936554f5823b328aaf8b651baa8db73e44  0.0s
 => CACHED [2/5] COPY .cog/tmp/build20240922140057.2656793537047400/requirements.txt /tmp/requirements.txt         0.0s
 => CACHED [3/5] RUN pip install --no-cache-dir -r /tmp/requirements.txt                                           0.0s
 => CACHED [4/5] RUN curl -o /usr/local/bin/pget -L "https://github.com/replicate/pget/releases/latest/download/p  0.0s
 => CACHED [5/5] WORKDIR /src                                                                                      0.0s
 => exporting to image                                                                                             0.0s
 => => exporting layers                                                                                            0.0s
 => => preparing layers for inline cache                                                                           0.0s
 => => writing image sha256:fcafea79f6e03de5ddbc9a062b9a49955214ec4e8c93d30a726e6d6d6d885957                       0.0s
 => => naming to docker.io/library/cog-flux-schnell-text2img--base                                                 0.0s

Running 'script/download-weights' in Docker with the current directory mounted as a volume...
[FATAL tini (8)] exec script/download-weights failed: No such file or directory
ⅹ exit status 127

**Comment by demoBBB** [comment]
I‘ve read the script and found that you dont need to run this line, just predict, and it will downloads the model. However, the base models are too large to download easily, but the script cant continue from last breakpoint. Maybe change it like wget will be better.

**Comment by asiryan** [comment]
Hello! Sorry for the confusion. This is my mistake, "download-weights" is unnecessary script. I have already removed it from README.md.
